// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALDkmQrR2-_PwIYkC1PA6w4rJ-T04e9E4',
    appId: '1:553895322711:web:ac5a84d25473015b2d2f12',
    messagingSenderId: '553895322711',
    projectId: 'iazkarapp',
    authDomain: 'iazkarapp.firebaseapp.com',
    storageBucket: 'iazkarapp.appspot.com',
    measurementId: 'G-SJDNN6P4FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-ZJGdLYgjoYnhnx90rNyRK7vcVKa4yA',
    appId: '1:553895322711:android:33162b7f114d2db32d2f12',
    messagingSenderId: '553895322711',
    projectId: 'iazkarapp',
    storageBucket: 'iazkarapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcwiZdfFb8dfJvfSSplHm68JbXeZJn48',
    appId: '1:553895322711:ios:e1b7a554f2bde63f2d2f12',
    messagingSenderId: '553895322711',
    projectId: 'iazkarapp',
    storageBucket: 'iazkarapp.appspot.com',
    iosBundleId: 'com.example.azkarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcwiZdfFb8dfJvfSSplHm68JbXeZJn48',
    appId: '1:553895322711:ios:e1b7a554f2bde63f2d2f12',
    messagingSenderId: '553895322711',
    projectId: 'iazkarapp',
    storageBucket: 'iazkarapp.appspot.com',
    iosBundleId: 'com.example.azkarapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALDkmQrR2-_PwIYkC1PA6w4rJ-T04e9E4',
    appId: '1:553895322711:web:10d7ddc8de1172882d2f12',
    messagingSenderId: '553895322711',
    projectId: 'iazkarapp',
    authDomain: 'iazkarapp.firebaseapp.com',
    storageBucket: 'iazkarapp.appspot.com',
    measurementId: 'G-2Q3B0R67Z6',
  );
}
