// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHuTPOU_5B2ndYNUFZZ1HB0-Hf4H9Fl5A',
    appId: '1:633568819720:web:7fcd9f9baabe487c84efbd',
    messagingSenderId: '633568819720',
    projectId: 'myapp-58c25',
    authDomain: 'myapp-58c25.firebaseapp.com',
    storageBucket: 'myapp-58c25.appspot.com',
    measurementId: 'G-3KC84MXRFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD567KNZfHmgFgr2hom8QS5zfnI0qlLxxU',
    appId: '1:633568819720:android:27ecf7393d97570684efbd',
    messagingSenderId: '633568819720',
    projectId: 'myapp-58c25',
    storageBucket: 'myapp-58c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUKsSZtb1DinF3TB4bnFwCje3tO9nJdbM',
    appId: '1:633568819720:ios:4fb961109db2957584efbd',
    messagingSenderId: '633568819720',
    projectId: 'myapp-58c25',
    storageBucket: 'myapp-58c25.appspot.com',
    iosBundleId: 'com.example.azkarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUKsSZtb1DinF3TB4bnFwCje3tO9nJdbM',
    appId: '1:633568819720:ios:4fb961109db2957584efbd',
    messagingSenderId: '633568819720',
    projectId: 'myapp-58c25',
    storageBucket: 'myapp-58c25.appspot.com',
    iosBundleId: 'com.example.azkarapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHuTPOU_5B2ndYNUFZZ1HB0-Hf4H9Fl5A',
    appId: '1:633568819720:web:4116814ca872f5d484efbd',
    messagingSenderId: '633568819720',
    projectId: 'myapp-58c25',
    authDomain: 'myapp-58c25.firebaseapp.com',
    storageBucket: 'myapp-58c25.appspot.com',
    measurementId: 'G-9N4VQWLK5F',
  );
}
